package chapter10_2.po;

public class TStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stuno
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    private Integer stuno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stuname
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    private String stuname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.grade
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.dept
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.classname
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    private String classname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stuno
     *
     * @return the value of t_student.stuno
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public Integer getStuno() {
        return stuno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stuno
     *
     * @param stuno the value for t_student.stuno
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public void setStuno(Integer stuno) {
        this.stuno = stuno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stuname
     *
     * @return the value of t_student.stuname
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stuname
     *
     * @param stuname the value for t_student.stuname
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public void setStuname(String stuname) {
        this.stuname = stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.grade
     *
     * @return the value of t_student.grade
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.grade
     *
     * @param grade the value for t_student.grade
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.dept
     *
     * @return the value of t_student.dept
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.dept
     *
     * @param dept the value for t_student.dept
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.classname
     *
     * @return the value of t_student.classname
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.classname
     *
     * @param classname the value for t_student.classname
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    public void setClassname(String classname) {
        this.classname = classname;
    }
}