package chapter10_2.dao;

import chapter10_2.po.TStudent;
import java.util.List;

public interface TStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    int deleteByPrimaryKey(Integer stuno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    int insert(TStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    TStudent selectByPrimaryKey(Integer stuno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    List<TStudent> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_student
     *
     * @mbg.generated Wed Jun 07 11:14:49 CST 2023
     */
    int updateByPrimaryKey(TStudent record);
}